insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'admin','admin','admin@admin.com','8334701','admin','A', '23226TE',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Meginarda','Herculano','mcodger@admin.com','833470221','12345','A', '23226T',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Linnea','Benancio','rasputin@admin.com','8302211221','12345','A', '23236M',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Meginarda','Baudolino','luismiguel@admin.com','8302323421','12345','A', '2356Q',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Lutero','Berardo','angelnaranjo@admin.com','83043323221','12345','A', '232321A',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Liuva','Berno','luis.alfredo@admin.com','83026721','12345','A', '232332456H',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Linnea','Calócero','sociovip@admin.com','83023521','12345','A', '23234TL',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Bertualda','Carino','clienta.selecta@admin.com','832230221','12345','A', '232336TO',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Melisenda','Casiodoro','clienta.tacaña@admin.com','81301221','12345','A', '2323456AS',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Loreley','Arrio','cliente.puntual@admin.com','83022781','12345','A', '23234536A',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Gúndula','Celio','cliente.adinerado@admin.com','835760221','12345','A', '23256P',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Ermenolda','Casiodoro','yocomprosiempre@admin.com','83034221','12345','A', '23456O',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Linnea','Berilo','gandalf.el.blanco@admin.com','830222221','12345','A', '23236K',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Grimoalda','Bono','legolas@admin.com','838670221','12345','A', '2334565F',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Lutero','Calpurnio','sauron@admin.com','8312560221','12345','A', '2839J',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Loreley','Hereno','mordor@admin.com','830121221','12345','A', '2323456T',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Lutero','Berardo','aun.mas.mordor@admin.com','83210221','12345','A', '2323456T',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Modoalda','Bonito','puerta.negra@admin.com','833210221','12345','A', '2323456T',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Lutarda','Ruy','tolkien@admin.com','8302323221','12345','A', '1323456A',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Ludgera','Cebrián','admin13459@admin.com','830242321','12345','A', '232323456B',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, dni,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Mainardo','Menendo','admin.muchos.datos@admin.com','830221233','12345','A', '2323456S',false,false,false);









insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'usuario','usuario','usuario@usuario.com','83021213','1234','C', '19',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Arduino','SAURON JR','papotemalote@usuario.com','560778','12345','C', '87',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Arabela','CARMELITO','yoakinocompronada@usuario.com','21121213','12345','C', '90',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Hunfrido','DRAKE','encripter@usuario.com','50221213','2345','C', '23',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Hildebrando','GOKU','bean@usuario.com','67021213','2345','C', '89',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Hildeberto','WENSESLAO','jdbc@usuario.com','23421213','2345','C', '15',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Hildeberta','NORRIS','mockaroo@usuario.com','24621213','2345','C', '17',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Teodefrido','PHILIP','megustaelbacalo@usuario.com','06921213','23457','C', '12',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Salaberga','SAMSAG','sakamoto@usuario.com','3121213','2345','C', '73',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Teofrida','TARGAERYEN','olaketal@usuario.com','596021213','2345','C', '23',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Vulfilda','STARK','usuario25667@usuario.com','5623404233','2345','C', '24',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Volfganga','LANNISTER','comoelagua@usuario.com','78980213','2345','C', '19',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Hadulfa','BARATHEON','fiestapagana@usuario.com','23021213','2345','C', '38',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Isarnio','STARMIE','obispadodesevilla@usuario.com','55021213','1453','C', '34',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Isarnia','PANTAN','abejamaya@usuario.com','0691213','12345','C', '20',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Ulfila','Lorelay','upracticas@usuario.com','832246021213','12345','C', '97',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Ricarda','Gontario','implementacion@usuario.com','673021213','12345','C', '35',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Teofrida','Grimoaldo','osmosis@usuario.com','8121323','12347','C', '39',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'usuario18','Liuva','usurapioo@usuario.com','8302121989','12349','C', '29',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Tula','Gumesindo','rapinorix@usuario.com','8302145763','12340','C', '79',false,false,false);
insert into  usuario(id, nombre,apellidos,email,telefono, password,dtype, edad,credenciales_caducadas,cuenta_bloqueada,cuenta_caducada) values (NEXTVAL('hibernate_sequence'),'Viduquinda','Gudulia','tutankamon@usuario.com','8304213','12343','C', '59',false,false,false);


insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramo 12', 'Ramo de 12 claveles', '2013-10-20', 23.67);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramo 15', 'Ramo de 15 claveles', '2018-06-10', 41.52);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramo 10', 'Ramo de 10 claveles', '2016-11-16', 8.59);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Bouquet', 'Bouquet enorme', '2014-02-09', 50.29);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Bouquet Amarillo', 'Bouquet amarilla mediano', '2014-10-10', 25.35);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Margarita', 'Set de Margaritas blancas', '2016-01-24', 73.25);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Margarita roja', 'Set de Margaritas rojas', '2013-11-17', 56.13);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Margarita amarilla', 'Set de Margaritas amarillas', '2012-07-25', 28.54);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Margarita violeta', 'Set de Margaritas violetas', '2015-04-11', 34.38);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Margarita azul', 'Set de Margaritas azules', '2018-10-08', 28.97);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Pintar flores de otro color', 'Con spray aplicamos una capa de pintura sobre su flor favorita', '2013-05-13', 23.78);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Corona florar mini', 'Corona de centro de mesa', '2018-01-27', 7.8);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramo de lagrimas de rosa espinada', 'Rosa espinada cristalizada', '2017-06-22', 76.85);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Petalos de rosa fresca', 'Petalos de rosas ', '2016-09-14', 38.72);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Arbusto bonsai mediano', 'Bonsai mediano con kit', '2012-09-02', 53.81);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Arbusto bonsai grande', 'Bonsai grande con kit', '2017-05-19', 75.68);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Arbusto bonsai pequeño', 'Bonsai pequeño con kit', '2012-05-27', 20.69);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flor pascua grande', 'Flor de la pascua grande', '2013-06-26', 84.25);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flor pascua pequeña', 'Flor de la pascua pequeña', '2013-07-09', 30.39);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flor pascua mediana', 'Flor de la pascua mediana', '2013-11-20', 58.67);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flor de elwyn', 'Flor del bosque de elwyn', '2017-03-18', 15.39);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flor de Lis', 'Lirio azul frances', '2013-07-17', 67.89);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Rosas amarilla paquete', 'Paquete completo', '2019-03-21', 72.95);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Rosas negras paquete', 'Paquete completo', '2017-06-20', 83.85);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Rosas violetas mini', 'Paquete completo', '2012-05-10', 4.02);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramo de rosas 6', 'Media docena de rosas', '2017-06-16', 38.99);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramo de rosas 12', 'Docena de rosas', '2017-09-21', 55.31);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Claveles rojos', 'Caja de claveles rojos', '2019-01-04', 86.42);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Claveles azules', 'Caja de claveles azules', '2013-11-19', 46.44);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Claveles amarillos', 'Caja de claveles amarillos', '2016-09-13', 29.56);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Claveles colores varios', 'Caja de claveles mixta', '2018-01-28', 79.49);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Mini centro de mesa', 'Mini centro de mesa completo', '2013-07-13', 12.82);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'La flor del general', 'Flor con motivo regio', '2014-07-02', 22.52);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Beso de sirena', 'Rosa azul cultiva en el mar', '2013-07-12', 44.57);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Lagrima de Myr', 'Rosa enquistada en un jarron elegante', '2013-05-29', 57.64);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Servicio por correo', 'Servicio por correo', '2019-02-18', 27.22);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Limpieza de sepultura', 'Limpieza semanal', '2017-08-20', 37.54);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Agua de mar(rosas)', 'Lagrimas de myr en formato pequeño', '2015-10-24', 10.5);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Siemprevivas rojas', 'Flores de verano duraderas', '2016-02-03', 18.49);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Siemprevivas blancas', 'Flores de verano duraderas', '2019-02-24', 83.78);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Centro "eterno" ', 'Flores de verano duraderas en centro de mesa', '2017-12-27', 78.94);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Siemprevivas azules', 'Flores de verano duraderas', '2019-02-11', 38.11);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Siemprevivas amarillas', 'Flores de verano duraderas', '2016-02-17', 6.77);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Lilios', 'Lilios blancos', '2015-07-20', 13.3);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Lisianthum', 'Flores de verano orientales', '2019-01-30', 13.98);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Centro de palma', 'Centro de palmas y rosas completo', '2012-04-13', 51.77);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Adornos varios', 'Set de adornos florales', '2017-04-24', 30.69);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Corona mediana', 'Corona funebre mediana', '2015-10-25', 84.17);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Centro de rosas', 'Centro de rosas completo', '2013-05-06', 63.41);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Rosa adiamantada', 'Rosa cristalizada en polvo de diamante', '2014-08-04', 88.38);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Rosa turca eterna', 'Rosa turca longeva', '2019-03-30', 32.36);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramillete', 'Ramillete de flores varias', '2012-11-02', 15.16);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Ramo de novia', 'Ramo de novia completo', '2019-04-11', 59.66);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Adornos de boda', 'Set de adornos de boda', '2017-07-24', 53.56);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Servicio de boda', 'Servicio de decoracion', '2013-12-23', 47.25);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flores de tela', 'Flores de tela con gran acabado', '2018-04-06', 45.4);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Aureola de claveles', 'Corona de claveles para Virgen', '2018-11-24', 77.0);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Corazon de tela', 'Flores de tela en forma de corazon', '2019-02-01', 26.05);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Claveles Thain', 'Claveles negros de la isla Thain', '2014-08-29', 38.56);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Brecha del norte', 'Lilio azul', '2017-02-25', 20.36);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'La flor de daenerys', 'Lilio rojo y amarillo', '2018-12-17', 12.85);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'El invierno se acerca', 'Lilio blanco con tonos azulados', '2017-02-19', 48.49);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Otoño primaveral', 'Bouquet en colores suaves y pasteles', '2017-06-06', 37.17);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Vida', 'Rosa Vida cultivada durante 1 año', '2017-11-10', 44.91);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Margaritas eternas', 'Margaritas duraderas(3 años)', '2018-06-09', 43.39);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),' Flor de Sadella', 'Flor de la isla de Sadella', '2013-10-23', 53.3);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),' Clavellina Carmon', 'Clavellina en color carmin', '2016-09-15', 18.05);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flor adamantis', 'La flor adamantis, elegante y bella', '2013-07-23', 40.58);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Pico de gallo', 'Llamado asi por su similaridad con el gallo', '2013-07-20', 83.35);
insert into producto (id,nombre, descripcion, fecha_Entrada, precio) values (NEXTVAL('hibernate_sequence'),'Flor de la coliflor', 'Brazika, una flor resistente al tiempo', '2017-06-17', 50.26);
